name: Discord

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Mensagens de alerta 1
                    Mensagens de alerta 2
                    Mensagens de alerta 3
                    Mensagens de alerta 4
                    Mensagens de alerta 5"